#!/usr/bin/env bash
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install nginx
sudo chown -R "$USER":"$USER" /var/www
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Helllo World " > /var/www/html/index.bginx.debian.html
sudo service nginx restart
